// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0a4UBc6R-IeS6KO0DxnWVYMRSGuhM9Hc',
    appId: '1:540099191662:web:5f6ee2fd115df2ef22577f',
    messagingSenderId: '540099191662',
    projectId: 'investor-9bc34',
    authDomain: 'investor-9bc34.firebaseapp.com',
    storageBucket: 'investor-9bc34.appspot.com',
    measurementId: 'G-0L27QXEG0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWWNXrW6C01G8StDVp1KJfZ0kU97jmkcQ',
    appId: '1:540099191662:android:207fc89f1fcf5c1522577f',
    messagingSenderId: '540099191662',
    projectId: 'investor-9bc34',
    storageBucket: 'investor-9bc34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpbfNDDeLL9269El2sN9PAHkqXRB5qvMo',
    appId: '1:540099191662:ios:5f51d07474ca1c5522577f',
    messagingSenderId: '540099191662',
    projectId: 'investor-9bc34',
    storageBucket: 'investor-9bc34.appspot.com',
    iosBundleId: 'com.example.investorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpbfNDDeLL9269El2sN9PAHkqXRB5qvMo',
    appId: '1:540099191662:ios:21ad730957231e5522577f',
    messagingSenderId: '540099191662',
    projectId: 'investor-9bc34',
    storageBucket: 'investor-9bc34.appspot.com',
    iosBundleId: 'com.example.investorapp.RunnerTests',
  );
}
